name = "wip-personal-site"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

[env.production]
name = "wip-personal-site"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat", "nodejs_als"]